// <auto-generated />
using aminofakeApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace aminofakeApi.Migrations
{
    [DbContext(typeof(FactsContext))]
    [Migration("20171017185703_First Letter Uppercase on facts prop")]
    partial class FirstLetterUppercaseonfactsprop
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("aminofakeApi.Models.Fact", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<bool>("IsFake");

                    b.Property<bool>("IsValidated");

                    b.Property<string>("Title");

                    b.HasKey("ID");

                    b.ToTable("Facts");
                });
#pragma warning restore 612, 618
        }
    }
}
